import os
import time
import pyautogui

print('login')
#os.system('firefox')
#time.sleep(5)
#pyautogui.write('https://solucoes.receita.fazenda.gov.br/Servicos/certidaointernet/PF/Emitir')
#pyautogui.hotkey('enter')
time.sleep(5)
#pyautogui.hotkey('ctrl','t')
#pyautogui.write('https://solucoes.receita.fazenda.gov.br/Servicos/certidaointernet/PF/Emitir')
#time.sleep(10)
#pyautogui.hotkey('enter')
pyautogui.click(2610,525)
time.sleep(2)
pyautogui.hotkey('tab')
pyautogui.write('40315446854')
pyautogui.hotkey('enter')
time.sleep(5)
pyautogui.hotkey('ctrl','f')
time.sleep(2)
pyautogui.write('de nova')
pyautogui.hotkey('enter')
time.sleep(2)
pyautogui.hotkey('esc')
pyautogui.hotkey('enter')
time.sleep(15)
pyautogui.hotkey('ctrl','w')
time.sleep(2)
pyautogui.click(2610,525)
pyautogui.hotkey('tab')
pyautogui.hotkey('enter')
time.sleep(3)
print('Terminou')